import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Providers } from "@/providers/nextUIProvider";
import AppSession from "@/providers/AppSession";
import { ToastContainer } from "react-toastify";
import { MiniAiChat } from "@/components/agent/components";
import { ChatProvider } from "@/components/agent/contexts/ChatContext";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
    <html suppressHydrationWarning className="h-full overflow-hidden">
      <body
        className={`${geistSans.variable} ${geistMono.variable} font-Helvetica antialiased bg-dark_blue h-full w-full overflow-hidden`}
      >
        <Providers>
          <AppSession>
            {children}
            <ChatProvider>
              <MiniAiChat />
            </ChatProvider>
            <ToastContainer
            position="bottom-right"
            autoClose={5000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="light"
            />
          </AppSession>
        </Providers>
      </body>
    </html>
  );
}
